server:
  port: 80
spring:
  application:
    name: server-GateWay
  cloud:
    nacos:

      discovery:
        server-addr: 43.142.147.67:8848
        username: nacos
        password: nacos
    #        ephemeral: false
    gateway:

      routes:
        #        授权微服务
        - id: server-authorization-route
          uri: lb://server-authorization
          predicates:
            - Path=/user/**,/admin/**
        #          filters:
        #            - StripPrefix=1 #转发之前去掉第一层路径
        # 电影服务
        - id: server-movie-route
          uri: lb://server-movie
          predicates:
            - Path=/movie/**
                  
        #mongo服务
        - id: server-mongo-route
          uri: lb://server-mongo
          predicates:
            - Path=/mongo/**
