server:
  port: 8930
spring:
  application:
    name: server-mongo
  cloud:
    nacos:

      discovery:
        server-addr: 43.142.147.67:8848
        username: nacos
        password: nacos
  #        ephemeral: false
  redis:
    host: 192.168.188.137
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
      
  data:
    mongodb:
      #      uri: mongodb://192.168.188.137:27017/easyMovie?authSource=admin
      uri: mongodb://192.168.188.137:27017/easyMovie