#feign:
#  httpclient:
#    enabled: false #开启httpclient支持
#    max-connections: 200
#    max-connections-per-route: 50
#  client:
#    config:
#      default:
#        loggerLevel: full #开启feign的日志
#logging:
#  level:
#    com.cxy.clients: debug #OpenFeign接口所在的包名


