server:
  port: 8920

spring:
  application:
    name: server-movie
  datasource:
    username: root
    password: 123456
    type: com.mysql.cj.jdbc.MysqlDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/em_movie?serverTimezone=GMT%2B8&characterEncoding=utf-8
  cloud:
    nacos:

      discovery:
        server-addr: 43.142.147.67:8848
        username: nacos
        password: nacos
        # ephemeral: false
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 1024MB
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
